### ISSUE TITLE
DHash calculate hash in C

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#11]
There is only one in Python now - it seems.
Get inspired by the blockhash implementation (loading images via libmagickwand):
https://github.com/commonsmachinery/blockhash

**Comment by dudaerich** [comment]
Sample implementation in python https://gist.github.com/dudaerich/eaf275eed32d386c0dcd

**Comment by klokan** [comment]
This is required for #10

**Comment by dudaerich** [comment]
The implementation is done, see https://github.com/moravianlibrary/dhash

However there is a problem. Surprisingly the implementation in C is several times slower than the Python implementation. The reason is that the PIL library can effective resize a Grayscale image, so the most expensive operation (resizing) is done very fast.

The ImagicMagick library transform RGB image to Grayscale in such way that it doesn't change the internal representation of image, but it set all RGB values to the same value. Then the resizing of the image is done in the same way as the original colored image.

I tried firstly resizing the image and then convert the image to Grayscale, but this technique was still slower than the Python implementation.

Tests were done on 45 316 images. Resultant times were produced by _time_ command.

|  | C | Python |
| --- | --- | --- |
| real | 10m37.567s | 3m55.814s |
| user | 22m5.424s | 3m53.981s |
| sys | 0m10.036s | 0m1.600s |

We can try to use another image processing library or use the Python implementation. I suggest to use Python implementation and also implement the imagesearch.mzk.cz web service in Python language. There is also Python implementation for Blockhash https://github.com/commonsmachinery/blockhash-python

**Comment by klokan** [comment]
We may probably need to do this in production environment with GDAL library anyway.
GDAL can operate on one band (grayscale) quite effectively and allows resizing with bilinear, etc.

**Comment by klokan** [comment]
Have you tried to enforce the colorspace?
It would be equivalent to command line calls: 
http://stackoverflow.com/questions/13317753/convert-rgb-to-grayscale-in-imagemagick-command-line
http://stackoverflow.com/questions/15399653/image-conversion-to-grayscale-using-imagemagick-is-very-dark

**Comment by dudaerich** [comment]
There is problem in resize function. It doesn't distinguish whether the image is Grayscale or RGBA. Grayscale image is internal saved as RGBA image (I see the code). PIL library uses special resize function for Grayscale images so it is more efficient.

We can increase speed by switching steps: transform to grayscale and resizing. If we firstly resize the image and then transform it, this change speeds up the process.

I try to use GDAL library and then I provide result of this investigation.

**Comment by dudaerich** [comment]
The GDAL library doesn't contain any "resize" function. There is only general transform function. The implementation of dhash would be difficult. I use the first implementation, which uses the ImageMagick.

**Comment by zabak** [comment]
What about GraphicsMagick? Should be faster. http://www.graphicsmagick.org/

**Comment by dudaerich** [comment]
We don't want to add additional dependencies on libraries. The ImageMagick was choosen because there is a BlockHash implementation that uses it.
