### ISSUE TITLE
Image hash comparation

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/imagesearch.mzk.cz#6]
As alternative for LIRE identity please compare performance of:
- BlockHash
- PHash (DCT / Radial / MM )
- DHash 

and basic comparing with Hamming distance (maybe hmsearch or brutal force).

To be part of article with basic documentation of these hashes.

**Comment by dudaerich** [comment]
## Blockhash
- [ ] Image divided to 4 quadrants M1 - M4.
- [ ] Each quadrant is divided to 8x8 blocks.
- [ ] For each block is computed value as sum of all R+G+B values of all pixels in the block.
- [ ] For each quadrant M1 - M4 is computed median (from block values).
- [ ] Each bit is simply set based on whether the value of block is less or bigger than competent median.

![image](https://cloud.githubusercontent.com/assets/2317374/6508202/ad64264e-c357-11e4-802b-5f8e041050ae.png)

## PHASH DCT
- [ ] Reduced to grayscale.
- [ ] Resize the image to 32x32.
- [ ] Compute the Discrete Cosine Transform (DCT) of the image. The DCT separates the image into a collection of frequencies and scalars.
- [ ] Just keep the top-left 8x8 of the DCT. While the DCT is 32x32, the top-left 8x8 represents the lowest frequencies in the picture.
- [ ] Compute the median value.
- [ ] Compute the hash from the DCT. Set the 64 hash bits to 0 or 1 depending on whether each of the 64 DCT values is above or below the median value.

## PHASH MH

We have developed a new image hash based on the Marr wavelet that computes a perceptual hash based on edge information with particular emphasis on corners. It has been shown that the human visual system makes special use of certain retinal cells to distinguish corner-like stimuli. It is the belief that this corner information can be used to distinguish digital images that motivates this approach. Basically, the edge information attained from the wavelet is compressed into a fixed length hash of 72 bytes. Binary quantization allows for relatively fast hamming distance computation between hashes. The following scatter plot shows the results on our standard corpus of images. The first plot shows the distances between each image and its attacked counterpart (e.g. the intra distances). The second plot shows the inter distances between altogether different images. While the hash is not designed to handle rotated images, notice how slight rotations still generally fall within a threshold range and thus can usually be matched as identical. However, the real advantage of this hash is for use with our mvp tree indexing structure. Since it is more descriptive than the dct hash (being 72 bytes in length vs. 8 bytes for the dct hash), there are much fewer false matches retrieved for image queries.

## DHASH

Introduced in http://blog.iconfinder.com/detecting-duplicate-images-using-python/
- [ ] Reduce size. The fastest way to remove high frequencies and detail is to shrink the image. In this case, shrink it to 9x8 so that there are 72 total pixels. (I'll get to the "why" for the odd 9x8 size in a moment.) By ignoring the size and aspect ratio, this hash will match any similar picture regardless of how it is stretched.
- [ ] Reduce color. Convert the image to a grayscale picture. This changes the hash from 72 pixels to a total of 72 colors. (For optimal performance, either reduce color before scaling or perform the scaling and color reduction at the same time.)
- [ ] Compute the difference. The dHash algorithm works on the difference between adjacent pixels. This identifies the relative gradient direction. In this case, the 9 pixels per row yields 8 differences between adjacent pixels. Eight rows of eight differences becomes 64 bits.
- [ ] Assign bits. Each bit is simply set based on whether the left pixel is brighter than the right pixel. The order does not matter, just as long as you are consistent. (I use a "1" to indicate that P[x] < P[x+1] and set the bits from left to right, top to bottom using big-endian.)

## Results

_PHash_dct_ gives bad results and _phash_mh_ is very slow. Candidates for searching of identity are _blockhash_ and _dhash_. In the next text we will consider only _blockash_ and _dhash_.

Both methods are unusable if query image has smaller size than indexed images. Query image must have at least size of indexed images.

### Testing data

Indexed 221 133 images of size 350px longer side
Searched 2122 images of size 350px longer side

### Results in numbers

<table>
  <tr>
    <th>Description</th>
    <th>Blockhash</th>
    <th>DHash</th>
  </tr>
  <tr>
    <td>Indexing time</td>
    <td>28m 18s</td>
    <td>15m</td>
  </tr>
  <tr>
    <td>Hash size</td>
    <td>256 bits</td>
    <td>64 bits</td>
  </tr>
</table>

Searching (350px longer side):

<table>
  <tr>
    <th>Description</th>
    <th>Blockhash</th>
    <th>DHash</th>
  </tr>
  <tr>
    <td>Searching time (bruteforce)</td>
    <td>3m 10s</td>
    <td>53s</td>
  </tr>
  <tr>
    <td>Average time for one image</td>
    <td>0.09s</td>
    <td>0.025s</td>
  </tr>
  <tr>
    <td>Distance of last found identity</td>
    <td>0.0546875</td>
    <td>0.078125</td>
  </tr>
  <tr>
    <td>Distance of first not found identity</td>
    <td>0.0546875</td>
    <td>0.09375</td>
  </tr>
</table>

Searching (1500px longer side):

<table>
  <tr>
    <th>Description</th>
    <th>Blockhash</th>
    <th>DHash</th>
  </tr>
  <tr>
    <td>Searching time (bruteforce)</td>
    <td>3m 10s</td>
    <td>53s</td>
  </tr>
  <tr>
    <td>Average time for one image</td>
    <td>0.09s</td>
    <td>0.025s</td>
  </tr>
  <tr>
    <td>Distance of last found identity</td>
    <td>0.0625</td>
    <td> 0.078125</td>
  </tr>
  <tr>
    <td>Distance of first not found identity</td>
    <td>0.0625</td>
    <td>0.09375</td>
  </tr>
</table>

_Note_: HmSearch results wasn't same as bruteforce.

## Conclusion

The best method is _dhash_. The reason is that the distance between last found identity and first not found identity is bigger than in _blockhash_ method (this method produces same distances for both images). Bonus is that _dhash_ uses shorter hash than blockhash, so the searching is much faster. It is necessary to reimplement the _dhash_ in C/C++ language. Current implementation in Python is not very robust, it can't read images in all image formats.

**Comment by dudaerich** [comment]
The developers of pHash library releases implementation of MVP tree as standalone data structure. See http://www.phash.org/download/ The implementation allows to store and retrieve records based on hamming distance. It should be compared with brute force technique.

**Comment by klokan** [comment]
+1 - to be done in #10 

On Wed, Apr 1, 2015 at 12:11 PM, Erich Duda notifications@github.com
wrote:

> The developers of pHash library releases implementation of MVP tree as
> standalone data structure. See http://www.phash.org/download/ The
> implementation allows to store and retrieve records based on hamming
> distance. It should be compared with brute force technique.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/moravianlibrary/imagesearch.mzk.cz/issues/6#issuecomment-88425426
> .

## 

Petr Pridal, Ph.D.
(managing director)

Klokan Technologies GmbH
Hofnerstrasse 96, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by klokan** [comment]
The conclusion has changed - based on the additional tests. Best to find identical images would be a combined search on Blockhash and DHash. Search system to be implemented in #10

**Comment by klokan** [comment]
Another comparation of the image hashing algorithms:
http://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html
http://www.hackerfactor.com/blog/?/archives/529-Kind-of-Like-That.html
